steps:
  # フロントエンドのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGISTRY}/frontend:${SHORT_SHA}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=${_API_BASE_URL}'
      - '.'
    dir: 'frontend'

substitutions:
  _REGISTRY: 'asia-northeast1-docker.pkg.dev/web-summarizer-app/app-reg'
  _API_BASE_URL: 'https://api.34.107.156.246.nip.io'
