steps:
  # フロントエンドのビルド
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - '${_REGISTRY}/frontend:${SHORT_SHA}'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_BASE_URL=${_API_BASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_GEMINI_API_KEY=${_GEMINI_KEY}'
      - '.'

  # イメージのプッシュ
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - '${_REGISTRY}/frontend:${SHORT_SHA}'

substitutions:
  _REGISTRY: 'asia-northeast1-docker.pkg.dev/web-summarizer-app/app-reg'
  _API_BASE_URL: 'https://api.34.107.156.246.nip.io'
  _GEMINI_KEY: ''
