apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: noncog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: api
          image: asia-northeast1-docker.pkg.dev/web-summarizer-app/app-reg/backend:ea19fe1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: ENABLE_KAFKA_PRODUCE
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENABLE_KAFKA_PRODUCE
            - name: ENABLE_KAFKA_CONSUME
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ENABLE_KAFKA_CONSUME
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_BOOTSTRAP_SERVERS
            - name: KAFKA_LEARN_EVENT_TOPIC
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_LEARN_EVENT_TOPIC
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: JWT_SECRET
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: DATABASE_URL
            - name: ALLOWED_ORIGINS
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: ALLOWED_ORIGINS
            - name: KAFKA_SECURITY_PROTOCOL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_SECURITY_PROTOCOL
            - name: KAFKA_SASL_MECHANISM
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: KAFKA_SASL_MECHANISM
            - name: KAFKA_SASL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: kafka-sasl-secret
                  key: KAFKA_SASL_USERNAME
            - name: KAFKA_SASL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: kafka-sasl-secret
                  key: KAFKA_SASL_PASSWORD
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 250m
              memory: 512Mi
            limits:
              cpu: 500m
              memory: 1Gi
        - name: cloud-sql-proxy
          image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.3
          args:
            - "--port=5432"
            - "--address=127.0.0.1"
            - "--credentials-file=/secrets/credentials.json"
            - "web-summarizer-app:asia-northeast1:noncog-pg"
          volumeMounts:
            - name: sql-proxy-key
              mountPath: /secrets
              readOnly: true
          securityContext:
            runAsNonRoot: true
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
      volumes:
        - name: sql-proxy-key
          secret:
            secretName: sql-proxy-key
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: noncog
  # Link BackendConfig for SSE long-lived connections (GKE Ingress)
  annotations:
    cloud.google.com/backend-config: '{"default": "backend-bec"}'
spec:
  type: NodePort
  selector:
    app: backend
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
      name: http
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: backend-hpa
  namespace: noncog
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: backend-bec
  namespace: noncog
spec:
  healthCheck:
    checkIntervalSec: 10
    timeoutSec: 5
    healthyThreshold: 1
    unhealthyThreshold: 3
    type: HTTP
    requestPath: /health
