apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml
  namespace: noncog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml
  template:
    metadata:
      labels:
        app: ml
    spec:
      containers:
        - name: ml
          image: asia-northeast1-docker.pkg.dev/web-summarizer-app/app-reg/ml:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: app-config
            - secretRef:
                name: app-secrets
          ports:
            - containerPort: 8001
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: ml
  namespace: noncog
spec:
  type: ClusterIP
  selector:
    app: ml
  ports:
    - port: 8001
      targetPort: 8001
      protocol: TCP
      name: http
