"""Create initial tables

Revision ID: 442d12d640c9
Revises: 83a4b42532e9
Create Date: 2025-09-14 10:02:09.521139

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "442d12d640c9"
down_revision = "83a4b42532e9"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
