"""Fix class models

Revision ID: 83a4b42532e9
Revises: 8d0a8fa379c0
Create Date: 2025-09-14 09:44:11.675622

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "83a4b42532e9"
down_revision = "8d0a8fa379c0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
