"""add avatar system tables only

Revision ID: add_avatar_tables_only
Revises: 0ea4d529c729
Create Date: 2025-09-14 15:45:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "add_avatar_tables_only"
down_revision = "0ea4d529c729"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create avatars table
    op.create_table(
        "avatars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "rarity", sa.String(length=20), nullable=False, server_default="common"
        ),
        sa.Column("unlock_condition_type", sa.String(length=50), nullable=True),
        sa.Column("unlock_condition_value", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"),
        sa.Column("sort_order", sa.Integer(), nullable=True, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_avatars_id"), "avatars", ["id"], unique=False)
    op.create_index(op.f("ix_avatars_name"), "avatars", ["name"], unique=True)

    # Create avatar_parts table
    op.create_table(
        "avatar_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=500), nullable=True),
        sa.Column("part_type", sa.String(length=50), nullable=False),
        sa.Column(
            "rarity", sa.String(length=20), nullable=False, server_default="common"
        ),
        sa.Column("unlock_condition_type", sa.String(length=50), nullable=True),
        sa.Column("unlock_condition_value", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"),
        sa.Column("sort_order", sa.Integer(), nullable=True, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_avatar_parts_id"), "avatar_parts", ["id"], unique=False)

    # Create titles table
    op.create_table(
        "titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("category", sa.String(length=50), nullable=False),
        sa.Column(
            "rarity", sa.String(length=20), nullable=False, server_default="common"
        ),
        sa.Column("unlock_condition_type", sa.String(length=50), nullable=False),
        sa.Column("unlock_condition_value", sa.Integer(), nullable=False),
        sa.Column("unlock_condition_description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True, server_default="true"),
        sa.Column("sort_order", sa.Integer(), nullable=True, server_default="0"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_titles_id"), "titles", ["id"], unique=False)
    op.create_index(op.f("ix_titles_name"), "titles", ["name"], unique=True)

    # Create user_avatars table
    op.create_table(
        "user_avatars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("avatar_id", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=True, server_default="false"),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["avatar_id"],
            ["avatars.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_avatars_id"), "user_avatars", ["id"], unique=False)

    # Create user_avatar_parts table
    op.create_table(
        "user_avatar_parts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("part_id", sa.Integer(), nullable=False),
        sa.Column("is_equipped", sa.Boolean(), nullable=True, server_default="false"),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["part_id"],
            ["avatar_parts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_avatar_parts_id"), "user_avatar_parts", ["id"], unique=False
    )

    # Create user_titles table
    op.create_table(
        "user_titles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title_id", sa.Integer(), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=True, server_default="false"),
        sa.Column(
            "unlocked_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["title_id"],
            ["titles.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_titles_id"), "user_titles", ["id"], unique=False)

    # Create user_stats table
    op.create_table(
        "user_stats",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column(
            "total_quests_completed", sa.Integer(), nullable=True, server_default="0"
        ),
        sa.Column(
            "daily_quests_completed", sa.Integer(), nullable=True, server_default="0"
        ),
        sa.Column(
            "current_streak_days", sa.Integer(), nullable=True, server_default="0"
        ),
        sa.Column("max_streak_days", sa.Integer(), nullable=True, server_default="0"),
        sa.Column(
            "total_learning_time_minutes",
            sa.Integer(),
            nullable=True,
            server_default="0",
        ),
        sa.Column("total_sessions", sa.Integer(), nullable=True, server_default="0"),
        sa.Column("grit_level", sa.Float(), nullable=True, server_default="1.0"),
        sa.Column(
            "collaboration_level", sa.Float(), nullable=True, server_default="1.0"
        ),
        sa.Column(
            "self_regulation_level", sa.Float(), nullable=True, server_default="1.0"
        ),
        sa.Column(
            "emotional_intelligence_level",
            sa.Float(),
            nullable=True,
            server_default="1.0",
        ),
        sa.Column(
            "total_titles_earned", sa.Integer(), nullable=True, server_default="0"
        ),
        sa.Column(
            "total_avatars_unlocked", sa.Integer(), nullable=True, server_default="0"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index(op.f("ix_user_stats_id"), "user_stats", ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_stats_id"), table_name="user_stats")
    op.drop_table("user_stats")
    op.drop_index(op.f("ix_user_titles_id"), table_name="user_titles")
    op.drop_table("user_titles")
    op.drop_index(op.f("ix_user_avatar_parts_id"), table_name="user_avatar_parts")
    op.drop_table("user_avatar_parts")
    op.drop_index(op.f("ix_user_avatars_id"), table_name="user_avatars")
    op.drop_table("user_avatars")
    op.drop_index(op.f("ix_titles_name"), table_name="titles")
    op.drop_index(op.f("ix_titles_id"), table_name="titles")
    op.drop_table("titles")
    op.drop_index(op.f("ix_avatar_parts_id"), table_name="avatar_parts")
    op.drop_table("avatar_parts")
    op.drop_index(op.f("ix_avatars_name"), table_name="avatars")
    op.drop_index(op.f("ix_avatars_id"), table_name="avatars")
    op.drop_table("avatars")
    # ### end Alembic commands ###
