name: Continuous Integration

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run Linter
        working-directory: ./frontend
        run: npm run lint

      - name: Type Check
        working-directory: ./frontend
        run: npm run type-check

      - name: Run Tests
        working-directory: ./frontend
        run: npm test

      - name: Build Check
        working-directory: ./frontend
        run: npm run build

  backend-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: |
            backend/requirements.txt
            ml/requirements.txt

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black isort mypy

      - name: Run Backend Linter
        working-directory: ./backend
        run: |
          black . --check
          isort . --check-only
          mypy .

      - name: Run Backend Tests
        working-directory: ./backend
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_db
          ENVIRONMENT: test
        run: |
          python -m pytest --cov=. --cov-report=xml

  ml-service-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: ml/requirements.txt

      - name: Install ML Dependencies
        working-directory: ./ml
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov black isort mypy

      - name: Run ML Service Linter
        working-directory: ./ml
        run: |
          black . --check
          isort . --check-only
          mypy .

      - name: Run ML Service Tests
        working-directory: ./ml
        run: |
          python -m pytest --cov=. --cov-report=xml

  # Dockerビルドテストは特定の条件でのみ実行
  docker-build-test:
    runs-on: ubuntu-latest
    needs: [frontend-test, backend-test, ml-service-test]
    if: |
      github.ref == 'refs/heads/main' ||
      github.ref == 'refs/heads/develop' ||
      contains(github.event.pull_request.files.*.path, '**/Dockerfile') ||
      contains(github.event.pull_request.files.*.path, '**/docker-compose.yml')
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend
        if: contains(github.event.pull_request.files.*.path, 'frontend/Dockerfile') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: false
          load: true
          tags: team21-frontend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Backend
        if: contains(github.event.pull_request.files.*.path, 'backend/Dockerfile') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: false
          load: true
          tags: team21-backend:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build ML Service
        if: contains(github.event.pull_request.files.*.path, 'ml/Dockerfile') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v5
        with:
          context: ./ml
          push: false
          load: true
          tags: team21-ml:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
