name: Basic CI Check

on:
  push:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - "backend/**"
  pull_request:
    branches: [main, develop]
    paths:
      - "frontend/**"
      - "backend/**"

jobs:
  frontend-check:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.files.*.path, 'frontend/') || contains(github.event.head_commit.modified, 'frontend/')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install and Check
        working-directory: ./frontend
        run: |
          npm ci
          npm run lint
          npm test

  backend-check:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.files.*.path, 'backend/') || contains(github.event.head_commit.modified, 'backend/')
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"
          cache-dependency-path: backend/requirements.txt

      - name: Install and Check
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          python -m pytest
