name: Gemini Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Setup Gemini API
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Run Gemini Code Review
        uses: google-github-actions/gemini-code-review@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          project-id: ${{ secrets.GCP_PROJECT_ID }}
          location: us-central1 # Gemini APIが利用可能なリージョン
          language: ja # 日本語でレビューコメントを生成
          review-comment-style: direct # 直接的なコメントスタイル
          max-files: 10 # レビューする最大ファイル数
          max-lines: 500 # レビューする最大行数
          exclude: |
            **/node_modules/**
            **/dist/**
            **/*.test.ts
            **/*.test.tsx
            **/*.spec.ts
            **/*.spec.tsx
