name: Gemini Code Review

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_review_comment:
    types: [created]

permissions:
  contents: read
  pull-requests: write

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: google/gemini-code-review@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          gemini-api-key: ${{ secrets.GEMINI_API_KEY }}
          language: ja # 日本語でレビューコメントを生成
          review-comment-style: direct # 直接的なコメントスタイル
          max-files: 10 # レビューする最大ファイル数
          max-lines: 500 # レビューする最大行数
          exclude: |
            **/node_modules/**
            **/dist/**
            **/*.test.ts
            **/*.test.tsx
            **/*.spec.ts
            **/*.spec.tsx
